# Generated by Django 6.0.4 on 2026-04-24 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Mirrors the Redis session UUID so the consumer can look it up cheaply.', unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='Set automatically when the record is created.')),
                ('end_time', models.DateTimeField(blank=True, help_text='Set when the first peer disconnects.', null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='end_time − start_time in whole seconds. Null while session is live.', null=True)),
                ('reported', models.BooleanField(db_index=True, default=False, help_text='True when either peer sends report_peer during the session.')),
                ('reported_at', models.DateTimeField(blank=True, help_text='Timestamp of the report.', null=True)),
                ('reported_by', models.ForeignKey(blank=True, help_text='The User who submitted the report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_reported', to=settings.AUTH_USER_MODEL)),
                ('user_one', models.ForeignKey(help_text='The peer who was already waiting in the pool (peer1 / answerer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_as_user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(help_text='The peer who arrived and triggered the match (peer2 / offerer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_as_user_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match session',
                'verbose_name_plural': 'Match sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
