# Generated by Django 6.0.4 on 2026-04-25 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this snapshot was taken.')),
                ('hour_bucket', models.DateTimeField(db_index=True, help_text='The calendar hour this snapshot represents (minute/second = 0).', unique=True)),
                ('total_connections', models.PositiveIntegerField(default=0, help_text='Value of ONLINE_COUNT_KEY at snapshot time.')),
                ('authenticated_users', models.PositiveIntegerField(default=0, help_text='SCARD of ONLINE_USERS_KEY at snapshot time.')),
                ('requests_in_hour', models.PositiveIntegerField(default=0, help_text='UserActivity rows whose timestamp falls in this hour bucket.')),
            ],
            options={
                'verbose_name': 'Traffic snapshot',
                'verbose_name_plural': 'Traffic snapshots',
                'ordering': ['-hour_bucket'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Client IP — X-Forwarded-For header respected for proxies/ngrok.')),
                ('location', models.CharField(default='Unknown', help_text='City, Country — resolved once per unique IP via ip-api.com.', max_length=120)),
                ('path', models.CharField(help_text='URL path of the request, e.g. /connect/.', max_length=512)),
                ('user_agent', models.TextField(blank=True, help_text='Raw HTTP User-Agent header.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for unauthenticated visitors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User activity',
                'verbose_name_plural': 'User activity logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='core_userac_ip_addr_632429_idx'), models.Index(fields=['user', 'timestamp'], name='core_userac_user_id_536d16_idx')],
            },
        ),
    ]
