# Generated by Django 6.0.4 on 2026-04-26 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trafficsnapshot_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short code used in WS messages, e.g. "3mm".', max_length=32, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable label shown in the UI.', max_length=64)),
                ('win_points', models.IntegerField(default=3)),
                ('draw_points', models.IntegerField(default=1)),
                ('loss_points', models.IntegerField(default=-1)),
                ('active', models.BooleanField(default=True, help_text='Deactivated game types are not offered to users.')),
            ],
            options={
                'verbose_name': 'Game type',
                'verbose_name_plural': 'Game types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_session_id', models.UUIDField(db_index=True, help_text='UUID of the parent MatchSession (not a FK to avoid coupling).')),
                ('is_win', models.BooleanField(default=False)),
                ('is_draw', models.BooleanField(default=False)),
                ('is_loss', models.BooleanField(default=False)),
                ('is_forfeit', models.BooleanField(default=False, help_text='True when the player disconnected mid-game.')),
                ('points_earned', models.IntegerField(default=0, help_text='Positive (win/draw) or negative (loss) delta applied to total score.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results', to=settings.AUTH_USER_MODEL)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='core.gametype')),
            ],
            options={
                'verbose_name': 'Game result',
                'verbose_name_plural': 'Game results',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'game_type', 'timestamp'], name='gr_user_game_ts')],
            },
        ),
    ]
