# Generated by Django 6.0.4 on 2026-04-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gametype_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='core.matchsession'),
        ),
    ]
