# Generated by Django 6.0.4 on 2026-04-27 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTermsAndPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions_agreed', models.BooleanField(default=False, help_text='User agrees to terms and acceptable use policy')),
                ('age_confirmation', models.BooleanField(default=False, help_text='User confirms they are at least 18 years old')),
                ('promotional_emails_agreed', models.BooleanField(default=False, help_text='User agrees to receive promotional emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_policy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Terms and Policy',
                'verbose_name_plural': 'User Terms and Policies',
            },
        ),
    ]
