# Generated by Django 6.0.4 on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usertermsandpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('recipient_scope', models.CharField(choices=[('selected', 'Selected users'), ('opted_in_all', 'All opted-in users')], max_length=20)),
                ('intended_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('excluded_count', models.PositiveIntegerField(default=0)),
                ('sent_recipients', models.JSONField(blank=True, default=list)),
                ('failed_recipients', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_send_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Email Send Log',
                'verbose_name_plural': 'Admin Email Send Logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
